applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = "persona_app"
urlpatterns = [
    path('', views.inicioView.as_view(), name='inicio'),
    path('list_all_employees/', views.ListAllEmployees.as_view(), name='empleados'),
    path('listbyarea/<shortname>/', views.ListByAreaEmpleado.as_view()),
    path('listbyjob/<job>/', views.ListByJobEmpleado.as_view()),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('habilidades/', views.ListHabilidades.as_view()),
    path('detail/<pk>/', views.EmpleadoDetail.as_view(),name='empleado_detail'),
    path('create/', views.CreateEmployee.as_view()),
    path('sucess/', views.SucessTemplate.as_view(), name='sucess'),
    path('update_employee/<pk>/', views.UpdateEmployee.as_view(), name='update_employee'),
    path('delete_employee/<pk>/', views.deleteEmpleado.as_view(), name='delete_employee'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employees/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #urls app departamento
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.persona.urls')),
    re_path('', include('applications.home.urls'))
]

applications/persona/models.py
from django.db import models
from applications.departamento.models import Departamento
# Create your models here.
from ckeditor.fields import RichTextField

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidades', max_length=50)


    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades empleado'

    def __str__(self):
        return str(self.id) + ' ' + self.habilidad

class Empleado(models.Model):
    """ Model empleado"""

    JOBS_CHOICES = (
        ('0', 'CONTADOR'),
        ('1', 'ADMINISTRADOR'),
        ('2', 'ECONOMISTA'),
        ('3', 'OTRO'),
    )
    first_name = models.CharField('Nombre', max_length=60)
    last_name = models.CharField('Apellido', max_length=60)
    full_name = models.CharField('Nombre completo', max_length=120, blank=True, null=True)
    job = models.CharField('Jobs', max_length=1, choices=JOBS_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado',blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField()


    class Meta:
        verbose_name = 'Mi Empleado'
        verbose_name_plural = 'Empleados de la empresa'
        ordering = ['first_name']
        unique_together = ('first_name', 'departamento')

    def __str__(self):
        return f'{str(self.id)} - {self.first_name}'

applications/persona/views.py
from django.shortcuts import render
from django.views.generic import (
    ListView, DetailView, CreateView, TemplateView, UpdateView, DeleteView
)
from .models import Empleado
from django.urls import reverse_lazy

# Create your views here.
class inicioView(TemplateView):
    template_name = 'inicio.html'


class ListAllEmployees(ListView):
    template_name = 'persona/list_all.html'
    paginate_by = 4
    model = Empleado
    context_object_name = 'empleados'

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", '')
        lista = Empleado.objects.filter(
            full_name__icontains=palabra_clave
        )
        return lista

class ListByAreaEmpleado(ListView):
    template_name = 'persona/listarea.html'

    def get_queryset(self):
        area = self.kwargs['shortname']
        lista = Empleado.objects.filter(
            departamento__short_name=area)
        return lista


class ListByJobEmpleado(ListView):
    template_name = 'persona/list_job.html'

    def get_queryset(self):
        job = self.kwargs['job']
        lista = Empleado.objects.filter(
            job=job)
        return lista


class ListEmpleadosByKword(ListView):
    template_name = 'persona/by_kword.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        kword = self.request.GET.get("kword","")
        element = Empleado.objects.filter(first_name=kword)
        return element


class ListHabilidades(ListView):
    template_name = 'persona/listhabilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        habilidades = Empleado.objects.get(id=5)
        return habilidades.all()


class EmpleadoDetail(DetailView):
    model = Empleado
    template_name = 'persona/detailempleado.html'

    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetail, self).get_context_data(**kwargs)
        context['titulo'] = 'Empleado del mes'
        return context

class SucessTemplate(TemplateView):
    template_name = "persona/sucess.html"


class CreateEmployee(CreateView):
    model = Empleado
    template_name = "persona/create_empleado.html"
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
    ]
    success_url = reverse_lazy('persona_app:empleados')

    def form_valid(self, form):
        empleado = form.save(commit=False)
        empleado.full_name = f'{empleado.first_name} {empleado.last_name}'
        empleado.save()
        return super(CreateEmployee, self).form_valid(form)


class UpdateEmployee(UpdateView):
    model = Empleado
    template_name = "persona/update_employee.html"
    fields = [
        'first_name',
        'last_name',
        'job'
    ]
    success_url = reverse_lazy('persona_app:empleados')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        return super(UpdateEmployee, self).form_valid(form)


class deleteEmpleado(DeleteView):
    model = Empleado
    template_name = "persona/delete_employee.html"
    success_url = reverse_lazy('persona_app:empleados')

templates/persona/by_kword.html
<h1>Buscar por palabra clave</h1>

<form method="get"> {% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Ingrese nombre aquí">
    <button type="submit">Buscar</button>
</form>

<h3>Lista resultados</h3>

<ul>
    {% for e in empleados %}
    <li>{{ e }}</li>
{% endfor %}

</ul>

templates/persona/create_empleado.html
<h1>Crear empleado</h1>

<form method="post"> {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enviar</button>
</form>

templates/persona/delete_employee.html
<h1>Eliminar</h1>

<form method="post"> {% csrf_token %}

    <p>Confirme que desea eliminar</p>
    <button type="submit">Confirmar</button>
</form>

templates/persona/detailempleado.html
<h1>Detalle de empleado {{ titulo }}</h1>

{{ empleado }}

<h3>Todos los datos </h3>

<p>{{ empleado.first_name }}</p>
<p>{{ empleado.last_name }}</p>
<p>{{ empleado.departamento }}</p>

templates/persona/list_all.html
{% extends 'base.html' %}

{% block content %}
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-7">
                <input type="text" id="kword" name="kword" placeholder="buscar empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                    <th width="200">ID</th>
                    <th>NOMBRE</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for empleado in empleados %}
                    <tr>

                        <TD>{{empleado.id}}</TD>
                    <TD>{{empleado.first_name}}</TD>
                    <TD>{{empleado.last_name}}</TD>
                    <TD>{{empleado.departamento}}</TD>
                    <td><a class="button warning" href="{% url 'persona_app:empleado_detail' empleado.id %}" >ver</a></td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>

        <div class="cell">
            {% if is_paginated %}
                    <nav aria-label="Pagination">
                      <ul class="pagination text-center">
                          {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">ATRAS</a>
                        </li>
                              {% endif %}


                      {% for page in paginator.page_range %}
                          {% ifequal page page_obj.number %}
                          <li class="current"><span class="show-for-sr">You're on page</span> {{page}}</li>
                              {% else %}
                              <li><a href="?page={{page}}">{{page}}</a></li>
                          {% endifequal %}

                      {% endfor %}
                      {% if page_obj.has_next %}
                        <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Next</a></li>
                          {% endif %}
                      </ul>
                    </nav>
                {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

templates/persona/list_job.html
<h1>Lista de todos los empleados por job</h1>

<ul>
{% for element in object_list %}
    <li>{{ element }}</li>
    {% endfor %}
</ul>

templates/persona/listarea.html
<h1>Lista de empleados por departamento</h1>

{% for empleado in object_list %}
<p>{{empleado}}</p>
{% endfor %}

templates/persona/listhabilidades.html
<h1>Habilidades de empleado</h1>

<ul>
{% for element in habilidades %}
    <li>{{ element }}</li>
    {% endfor %}
</ul>

templates/persona/sucess.html
<h1>FELICIDADES</h1>

templates/persona/update_employee.html
<h1>Actualizar empleado</h1>

<form method="post"> {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enviar</button>
</form>